# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 010672e7403efcc688f8a1dda483d6c02df4ab454505700137183d3deafeeb677e76e61c107a4deeffc93b2320a20b9c7816bc78a56b5d99e59c857fb4056b2b

test:
  secret_key_base: d8dfad3c91ab87153e531860f6509318d76f9f00cdf0573af88da378a847d1f404dc6fae95252b1b31a846fe9cd9a59cca5297d905e371b264cfd5b8b81f2f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
